name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to Issues! Please be sure to read the contribution guidelines and Code of Conduct before Contributing'
        pr-message: 'Welcome to Pull Requests! Please be sure to read the contribution guidelines and Code of Conduct before Contributing'
